export const NEED_ACCOUNT_REFRESH = 'NEED_ACCOUNT_REFRESH';    
export const PING_REPLY = 'ping_REPLY';
export const GET_ACCOUNTS_RESULT = 'GET_ACCOUNTS_RESULT';
export const GET_TAB_GROUPS_RESULT = 'GET_TAB_GROUPS_RESULT';
export const GET_TAB_NEW_EVENT = 'GET_TAB_NEW_EVENT'; // TAB_GET_NEW の応答。要するにツイート
